# config/_default/languages.zh-tw.toml
languageCode = "zh-tw"
languageName = "繁體中文"
weight = 4
title = ""

[params]
  displayName = "繁體中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/setting/LogoLight.png"
  secondaryLogo = "img/setting/LogoDark.png"
  description = "Liu Zhe You's Developer Blog"

  [author]
    name = "Liu Zhe You"
    image = "img/setting/Profile.jpeg"
    headline = "Apache Airflow Committer / Intern @Appier / CSIE @NCKU"
    # show in author avatar bottom
    bio = "專注在貢獻開源、Distributed System、Data Engineering"
    links = [
      { github = "https://github.com/jason810496" },
      { linkedin = "https://linkedin.com/in/zhe-you-liu/" },
      { email = "mailto:jasonliu@apache.org" }
    ]
