# config/_default/languages.zh-tw.toml
languageCode = "zh-tw"
languageName = "繁體中文"
weight = 4
title = ""

[params]
  displayName = "繁體中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/LogoLight.png"
  secondaryLogo = "img/LogoDark.png"
  description = "這是我的網站"

[author]
name = "Liu Zhe You"
image = "img/Profile.jpeg"
headline = "Intern @Appier / CSIE @NCKU"
bio = "一些關於我的介紹" # show in author avatar bottom
links = [
  { github = "https://github.com/jason810496" },
  { linkedin = "https://linkedin.com/in/zhe-you-liu/" },
  { email = "mailto:810496@email.wlsh.tyc.edu.tw" }
]
