# config/_default/languages.en.toml
languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/setting/LogoLight.png"
  secondaryLogo = "img/setting/LogoDark.png"
  description = "Zhe-You Liu's Developer Blog"

  [author]
    name = "Zhe-You Liu"
    image = "img/setting/Profile.jpeg"
    headline = "Apache Airflow Committer / Intern @Appier / CSIE @NCKU"
    # show in author avatar bottom
    bio = "Focused on Contributing to open source, Distributed Systems, and Data Engineering."
    links = [
      { github = "https://github.com/jason810496" },
      { linkedin = "https://linkedin.com/in/zhe-you-liu/" },
      { email = "mailto:jasonliu@apache.org" }
    ]

