# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "tags/blog"
  weight = 10

[[main]]
  name = "分類"
  pageRef = "categories"
  weight = 20

# Nested Menu for Categories
[[main]]
  name = "實習經歷"
  parent = "分類"
  pageRef = "tags/intern"
  weight = 11

[[main]]
  name = "開源貢獻"
  parent = "分類"
  pageRef = "tags/open-source-contribution"
  weight = 20

[[main]]
  name = "資料庫"
  parent = "分類"
  pageRef = "tags/database"
  weight = 21

[[main]]
  name = "後端"
  parent = "分類"
  pageRef = "tags/backend"
  weight = 22

[[main]]
  name = "DevOps"
  parent = "分類"
  pageRef = "tags/devops"
  weight = 23

[[main]]
  name = "資料工程"
  parent = "分類"
  pageRef = "tags/data-engineering"
  weight = 24

[[main]]
  name = "所有標籤"
  parent = "分類"
  pageRef = "tags"
  weight = 25


[[main]]
  pre = "github"
#   name = "GitHub"
  identifier = "github"
  url = "https://github.com/jason810496/"
  weight = 30

[[main]]
  pre = "linkedin"
#   name = "LinkedIn"
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/zhe-you-liu/"
  weight = 40

# [[footer]]
#   name = "Privacy"
#   url = "https://external-link"
