# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

# Nested Menu for Topics
[[main]]
  name = "Database"
  parent = "Topics"
  pageRef = "samples"
  weight = 21

[[main]]
  name = "Backend"
  parent = "Topics"
  pageRef = "backend"
  weight = 22

[[main]]
  name = "Testing"
  parent = "Topics"
  pageRef = "samples"
  weight = 23

[[main]]
  name = "Tags"
  parent = "Topics"
  pageRef = "tags"
  weight = 24

[[main]]
  pre = "github"
#   name = "GitHub"
  identifier = "github"
  url = "https://github.com/jason810496/"
  weight = 30

[[main]]
  pre = "linkedin"
#   name = "LinkedIn"
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/zhe-you-liu/"
  weight = 40

[[footer]]
  name = "Privacy"
  url = "https:/github.com/jason810496/"
