# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "tags/blog"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

# Nested Menu for Categories
[[main]]
  name = "Database"
  parent = "Categories"
  pageRef = "tags/database"
  weight = 21

[[main]]
  name = "Backend"
  parent = "Categories"
  pageRef = "tags/backend"
  weight = 22

[[main]]
  name = "DevOps"
  parent = "Categories"
  pageRef = "tags/devops"
  weight = 23

[[main]]
  name = "Tags"
  parent = "Categories"
  pageRef = "tags"
  weight = 24

[[main]]
  pre = "github"
#   name = "GitHub"
  identifier = "github"
  url = "https://github.com/jason810496/"
  weight = 30

[[main]]
  pre = "linkedin"
#   name = "LinkedIn"
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/zhe-you-liu/"
  weight = 40

# [[footer]]
#   name = "Privacy"
#   url = "https:/github.com/jason810496/"
