# config/_default/menus.toml

[[main]]
  name = "Resume"
  url = "https://www.zhu424.dev/Resume/LIU_ZHE_YOU.pdf"
  weight = 10

[[main]]
  name = "Talks"
  url = "https://www.zhu424.dev/slides"
  weight = 15

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "OSS Contribution"
  parent = "Categories"
  pageRef = "tags/open-source-contribution"
  weight = 20

  
[[main]]
  name = "Database"
  parent = "Categories"
  pageRef = "tags/database"
  weight = 21

[[main]]
  name = "Backend"
  parent = "Categories"
  pageRef = "tags/backend"
  weight = 22

[[main]]
  name = "DevOps"
  parent = "Categories"
  pageRef = "tags/devops"
  weight = 23

[[main]]
  name = "Data Engineering"
  parent = "Categories"
  pageRef = "tags/data-engineering"
  weight = 24

[[main]]
  name = "Tags"
  parent = "Categories"
  pageRef = "tags"
  weight = 25

[[main]]
  pre = "github"
#   name = "GitHub"
  identifier = "github"
  url = "https://github.com/jason810496/"
  weight = 30

[[main]]
  pre = "linkedin"
#   name = "LinkedIn"
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/zhe-you-liu/"
  weight = 40

[[main]]
  pre = "rss"
  title = "RSS"
  identifier = "rss"
  url = "/index.xml"
  weight = 50

# [[footer]]
#   name = "Privacy"
#   url = "https:/github.com/jason810496/"
